server:
  port: 8866
spring:
  datasource:
    url: jdbc:mysql://192.168.159.8:3306/micromall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zw726515@
    druid:
      initial-size: 5 #���ӳس�ʼ����С
      min-idle: 10 #��С����������
      max-active: 20 #���������
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #��ͳ����Щ��������
      stat-view-servlet: #���ʼ����ҳ�ĵ�¼�û���������
        login-username: druid
        login-password: druid
  application:
    name: tulingmall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.8:8848
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #����SpringBoot Admin�ļ��
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
